export const fonts = {
  bold: 'TwCenMTStd-Bold',
  boldCond: 'TwCenMTStd-BoldCond',
  extraBold: 'TwCenMTStd-ExtraBold',
  extraBoldCond: 'TwCenMTStd-ExtraBoldCond',
  italic: 'TwCenMTStd-Italic',
  light: 'TwCenMTStd-Light',
  lightItalic: 'TwCenMTStd-LightItalic',
  mediumCond: 'TwCenMTStd-MediumCond',
  semiMedium: 'TwCenMTStd-SemiMedium',
  ultraBold: 'TwCenMTStd-UltraBold',
  ultraBoldCond: 'TwCenMTStd-UltraBoldCond',
  ultraBoldIt: 'TwCenMTStd-UltraBoldIt',
  regular: 'TwCenMTStd',
}